### ISSUE TITLE
ElMuchacho

### ISSUE THREAD

**Issue by eepykate** [druskus20/elkontest#13]
<h1>ElMuchacho</h1>
<p align="center">
  <img width="400" src="https://user-images.githubusercontent.com/40295114/91669628-94d7aa80-eb59-11ea-9e3c-17b78b1b231d.png">
</p>

original submission: https://user-images.githubusercontent.com/40295114/91669346-91432400-eb57-11ea-953f-ccccd6d0a213.png

https://cdn.discordapp.com/attachments/668436575767494680/740581793878638622/el_muchacho.mp4

**Comment by druskus20** [comment]
deep lore i dont understand
