### ISSUE TITLE
adding pictures I've made before but didn't submit

### ISSUE THREAD

**Issue by dnl32** [druskus20/elkontest#15]
- **Elkobrain**
![4f871e18-0d87-4e28-b0cf-eaba25f9c16f](https://user-images.githubusercontent.com/68392616/100390718-0bd9ed80-303a-11eb-8c07-ced1962f28cd.png)

- **ElKoberg**
![c51876ed-0b11-4dcc-8c65-d5b7fc7e59cf](https://user-images.githubusercontent.com/68392616/100390726-1300fb80-303a-11eb-9646-c53898f00bb6.png)
- **ElKowarn**
![b39990c6-e298-4f08-9e74-e7dce6880f33](https://user-images.githubusercontent.com/68392616/100390753-2b711600-303a-11eb-8068-9d03edce96bc.png)
- **rElkursion**
![3150cda3-5ac5-44cb-822f-79e1992f2b71](https://user-images.githubusercontent.com/68392616/100390766-362bab00-303a-11eb-9eaa-58a8560412e3.png)
- **ElKeyboard**
![03d51666-0f72-4581-944b-561e093ccde1](https://user-images.githubusercontent.com/68392616/100390775-3d52b900-303a-11eb-96e3-8c52a49e4571.png)
- **Elk o' war**
![c0c1abe7-4164-4b86-8671-84feb4aaadfb](https://user-images.githubusercontent.com/68392616/100390790-45aaf400-303a-11eb-892a-548776887a8b.png)
- **GKowar**
![08f62ec2-4d20-48eb-b8c9-a5bc02719d04](https://user-images.githubusercontent.com/68392616/100390813-52c7e300-303a-11eb-8683-4f1ed9857b6f.png)

**Comment by chxp82q** [comment]
@l1nusd you are a legend

**Comment by druskus20** [comment]
yes this

**Comment by safinsingh** [comment]
godly
