### ISSUE TITLE
submit by l1nus

### ISSUE THREAD

**Issue by dnl32** [druskus20/elkontest#4]
![26fd00df-fc86-4df4-85f4-187cd3f642a1](https://user-images.githubusercontent.com/68392616/88847972-7dbb3b00-d1f0-11ea-9a82-2c11e0ad622d.png)
![26fd00df-fc86-4df4-85f4-187cd3f642a2](https://user-images.githubusercontent.com/68392616/88847982-801d9500-d1f0-11ea-8603-71fbffcb64db.png)

**Comment by druskus20** [comment]
wow. 
Thats good
